### ISSUE TITLE
Remove setColumns method to helper

### ISSUE THREAD

**Issue by ekevra** [VyacheslavRadyuk/sf-senla-courses#102]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/423e0c5ca36dd129bb495ec32c3962632b9eda3a/lecture_3.4/RegistrationOfTripsController.js#L3

!And break it down into lines to make it look like this:
[
   {
      "label":"Tourist Name",
      "fieldName":"linkName",
      "type":"url",
      "typeAttributes":{
         "label":{
            "fieldName":"Name"
         },
         "target":"_blank"
      }
   },
   {
      "label":"Email",
      "fieldName":"Email__c",
      "type":"email",
      "initialWidth":300
   },
   {
      "label":"Gender",
      "fieldName":"Gender__c",
      "type":"picklist",
      "initialWidth":95
   }
]

**Comment by VyacheslavRadyuk** [comment]
done
