### ISSUE TITLE
Too many apex methods

### ISSUE THREAD

**Issue by ekevra** [VyacheslavRadyuk/sf-senla-courses#108]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/423e0c5ca36dd129bb495ec32c3962632b9eda3a/lecture_3.4/DataTableAuraServices.cls#L44

Слишком много запросов на сторону Apex, ведь производится один и тот же запрос в менеджер.
Если на стороне клиента действительно нужны все эти данные, можно их объединить во враппер, что позволит сократить кол-во сокл запросов и запросов на сторону сервера.

**Comment by VyacheslavRadyuk** [comment]
removed methods, added recordData
