### ISSUE TITLE
2.5 Return result (tourists)

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#20]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/f5feead2cf8dd06b8bf638e4fc20ab47219974be/lecture_2.5/AsynchTouristService.cls#L5

**Comment by NikitaErmakSenla** [comment]
If you make some update inside collection you should return it back and assign to collection:
`newTourists = TouristService.markDuplicates(newTourists, touristIds); `

**Comment by VyacheslavRadyuk** [comment]
+

**Comment by VyacheslavRadyuk** [comment]
done
