### ISSUE TITLE
2.5 Update existing method in TouristService

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#21]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/f5feead2cf8dd06b8bf638e4fc20ab47219974be/lecture_2.5/AsynchTouristService.cls#L1

**Comment by NikitaErmakSenla** [comment]
You can change name to `markDuplicatesAsync()`

**Comment by VyacheslavRadyuk** [comment]
done
