### ISSUE TITLE
2.5 All literals to Constants

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#25]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/f5feead2cf8dd06b8bf638e4fc20ab47219974be/lecture_2.5/Batch.cls#L12

**Comment by NikitaErmakSenla** [comment]
`Constants.FLIGHT_STATUS_DECLINED`

**Comment by VyacheslavRadyuk** [comment]
done
