### ISSUE TITLE
2.5 Format : remove line

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#27]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/f5feead2cf8dd06b8bf638e4fc20ab47219974be/lecture_2.5/Batch.cls#L18

**Comment by NikitaErmakSenla** [comment]
No need for break line before for() if it's first method line

**Comment by NikitaErmakSenla** [comment]
Still relevant

**Comment by VyacheslavRadyuk** [comment]
done
