### ISSUE TITLE
2.5.2 class.getName()

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#42]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/008843861c3a7491f06544ceba8082bf0382c328/lecture_2.5/BatchApexErrorEventTriggerHandler.cls#L15

**Comment by NikitaErmakSenla** [comment]
Why not DeleteFlightsBatch.class.getName()?

**Comment by VyacheslavRadyuk** [comment]
done
