### ISSUE TITLE
2.5.2 Async is a common shortcut (not asynch)

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#44]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/008843861c3a7491f06544ceba8082bf0382c328/lecture_2.5/TouristServiceAsynch.cls#L1

**Comment by VyacheslavRadyuk** [comment]
removed the class, the logic was moved to the handler

**Comment by VyacheslavRadyuk** [comment]
done
