### ISSUE TITLE
2.6.1 inappropriate use for try / catch

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#53]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/a8ee714c424fc8af101f4f6bdb720e866fae8c46/lecture_2.6/TouristRestService.cls#L25

**Comment by NikitaErmakSenla** [comment]
String.isNumeric()

**Comment by VyacheslavRadyuk** [comment]
done
