### ISSUE TITLE
2.6.1 incorrect naming by requirements

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#57]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/a8ee714c424fc8af101f4f6bdb720e866fae8c46/lecture_2.6/TouristRestService.cls#L9

**Comment by VyacheslavRadyuk** [comment]
done

**Comment by NikitaErmakSenla** [comment]
still relevant

**Comment by VyacheslavRadyuk** [comment]
done

**Comment by NikitaErmakSenla** [comment]
Still relevant (_name_ -> _fuzzyname_)

**Comment by VyacheslavRadyuk** [comment]
done)))
