### ISSUE TITLE
2.6.1 bad naming

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#63]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/a8ee714c424fc8af101f4f6bdb720e866fae8c46/lecture_2.6/WeatherForecastUpdater.cls#L9

**Comment by NikitaErmakSenla** [comment]
E.g. _forecastMap_, _forecastByDates_

**Comment by VyacheslavRadyuk** [comment]
done
