### ISSUE TITLE
2.2 clarify the logic 

### ISSUE THREAD

**Issue by alexCherrySfds2019** [VyacheslavRadyuk/sf-senla-courses#7]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/c3798d470b18c36471923ec07acf81e46dd47438/lecture_2.2/TouristService.cls#L1

а можешь в общем рассказать что делает метод? разбить на несколько шагов и описать что делает каждый?

**Comment by VyacheslavRadyuk** [comment]
![image](https://user-images.githubusercontent.com/68953404/111783293-1e1eb680-88cb-11eb-8ee5-89c8187cd46c.png)
/*в строчках 27-34 создается 2 экземпляра туриста. далее в 26 создается пустой лист туристов, в 35-36 в этот пустой лист добавляется наш созданный ранее турист.
в 37 строке вызываем наш метод. в 3 строке инсертим наш список добавленных туристов. в 4 строке добавляем в лист всех туристов с нужными нам полями(из турист менеджера, где хранится наш запрос).
создаем лист дубликатов в 5 строке, в 7 строке начинаем первый цикл перебора всего списка туристов, так же добавляем счетчик так как СТАРЫЙ турист из первого и СТАРЫЙ турист второго циклов одного id не должны быть добавлены в дубликаты,
так как это один и тот же турист.  в 10 строке начинаем второй цикл перебора( сравниваем по очереди туриста из первого цикла со всеми туристами в списке). 12 строка если совпадает емейл и имя, то прибавить к счетчику 1
далее ,когда мы отсеяли СТАРЫХ туристов, у нас осталось в 15 строчке проверить айдишники НОВЫХ туристов и если они совпадают добавить в лист дубликатов. Прикладываю файл с общей схемой в комментарии к issue. 
*/

**Comment by alexCherrySfds2019** [comment]
честно говоря не совсем понял твою логику, но общий смысл - ты вставляешь новых, потом выбираешь и ищешь дубликаты. Не совсем понял зачем так, и как потом определить новые/старые, опять же не понятно зачем тогда параметр.

В общем схема должна быть такая:
1) приходит список туристов (их еще нет в базе).
2) ты запрашиваешь из базы только необходимых туристов для оценки есть среди новых дубликаты или нет ( тех, которые имеют определенные значения полей)
3) оцениваешь, есть среди новых дубликаты или нет
4) если есть - отмечаешь его как дубликат

старые туристы (из базы) никак не меняются

**Comment by alexCherrySfds2019** [comment]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/b75832b256a1dfe5b3f40cd71770c0a8b7e1681f/lecture_2.2/TouristService.cls#L7

уже лучше, но у тебя запрос в цикле. Надо вынести запрос из цикла 
 (как рассмотрено в примере №2)https://developer.salesforce.com/wiki/apex_code_best_practices
