### ISSUE TITLE
2.6.2

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#72]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/2c8abbad38ee23c5936dd8445aabf1c929daecda/lecture_2.6/TouristRestService.cls#L38

**Comment by NikitaErmakSenla** [comment]
if method is used only inside class => private

**Comment by VyacheslavRadyuk** [comment]
done
