### ISSUE TITLE
2.6.2 Naming

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#77]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/2c8abbad38ee23c5936dd8445aabf1c929daecda/lecture_2.6/WeatherForecastUpdater.cls#L12

**Comment by NikitaErmakSenla** [comment]
Why forecastId? It's not id

E.g. forecast, forecastDate

**Comment by VyacheslavRadyuk** [comment]
done
