### ISSUE TITLE
2.6.2 Bad implementation

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#79]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/2c8abbad38ee23c5936dd8445aabf1c929daecda/lecture_2.6/TouristRestService.cls#L46

**Comment by NikitaErmakSenla** [comment]
1. getTouristsValidationTrue - bad naming. 
E.g. - handleValidationError

2. If Age wasn't filled - it's not validation error. This logic i ssupposed to be in getTourists() method

**Comment by VyacheslavRadyuk** [comment]
done
