### ISSUE TITLE
2.6.2 Bad implementation

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#80]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/2c8abbad38ee23c5936dd8445aabf1c929daecda/lecture_2.6/TouristRestService.cls#L12

**Comment by NikitaErmakSenla** [comment]
To add new validation you will need to add new condition to both places. Not good
Try throw ValidationException as discussed (check latest lection)

**Comment by VyacheslavRadyuk** [comment]
done
