### ISSUE TITLE
2.7.2 System class is imported everywhere

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#90]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/0bd2c1fa560504775a81879a00056352e125ad52/lecture_2.7/TouristManagerTest.cls#L183

**Comment by NikitaErmakSenla** [comment]
`Test.setFixedSearchResults(fixedSearchResults);`

**Comment by VyacheslavRadyuk** [comment]
done
