### ISSUE TITLE
2.7.2 Bad Naming

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#91]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/0bd2c1fa560504775a81879a00056352e125ad52/lecture_2.7/TouristManagerTest.cls#L9

**Comment by NikitaErmakSenla** [comment]
Why `touristsToInsert`? Later they are not inserted. Just `tourists` is ok

**Comment by VyacheslavRadyuk** [comment]
done
