### ISSUE TITLE
2.7.2 Order can be different

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#92]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/0bd2c1fa560504775a81879a00056352e125ad52/lecture_2.7/TripManagerTest.cls#L20

**Comment by NikitaErmakSenla** [comment]
You can't rely on the same order. You can check size() or check if return value contains needed ids

**Comment by VyacheslavRadyuk** [comment]
done
