### ISSUE TITLE
2.7.2 DRY

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#93]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/0bd2c1fa560504775a81879a00056352e125ad52/lecture_2.7/TouristTriggerTest.cls#L45

**Comment by NikitaErmakSenla** [comment]
Create private method in test class for SOQL (if there is no suitable method in Manager)

**Comment by VyacheslavRadyuk** [comment]
done
