### ISSUE TITLE
2.7.2 Always true (L18-20)

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#94]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/0bd2c1fa560504775a81879a00056352e125ad52/lecture_2.7/BatchApexErrorEventTriggerTest.cls#L18

**Comment by NikitaErmakSenla** [comment]
Compare against Error_Log record

**Comment by VyacheslavRadyuk** [comment]
done
