### ISSUE TITLE
2.7.2 Mocks should not be combined this way

### ISSUE THREAD

**Issue by NikitaErmakSenla** [VyacheslavRadyuk/sf-senla-courses#95]
https://github.com/VyacheslavRadyuk/sf-senla-courses/blob/0bd2c1fa560504775a81879a00056352e125ad52/lecture_2.7/WeatherForecastHttpCalloutMock.cls#L9

**Comment by NikitaErmakSenla** [comment]
Options:
1, Create several classes (inner classes?) for each Mock type;
2. Use class Contructor to define Mock type. BUT you should avoid situation where Mock has error Status Code bud have 'good' response body

**Comment by VyacheslavRadyuk** [comment]
done
